language: node_js
node_js:
    - 10
    - 9
    - 8
    - 7
    - 6
install:
    - npm install

script:
    - npm test
    - codecov -f coverage/*.json
    - npm i -g babel
    - npm run build
    - rsync -avh --progress ./types/ ./

jobs:
    include:
        - stage: deploy
          on:
              branch: remake
          deploy:
              provider: npm
              tag: beta
              edge: true
              email: '$NPM_EMAIL'
              api_key: '$NPM_API_TOKEN'
