language: node_js
sudo: false
node_js:
  - 10
  - 9
  - 8
  - 7
  - 6
install:
  - npm install

jobs:
  include:
    - stage: test
      script:
        - npm test
        - codecov -f coverage/*.json
        - npm i -g babel
        - npm run build
        - rsync -avh --progress ./types/ ./
    - stage: deploy
      deploy:
        provider: npm
        edge: true
        email: "$NPM_EMAIL"
        api_key: "$NPM_API_TOKEN"
        skip_cleanup: true
        on:
          branch: remake
