language: node_js
sudo: false
node_js:
  - 10
  - 9
  - 8
  - 7
  - 6
install:
  - npm install
script:
  - npm test
  - codecov -f coverage/*.json
  - rsync -avh --progress ./types/ ./
  - find . -type d | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"
