version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    working_directory: ~/cko-node
    docker:
      - image: circleci/node:11.14.0 
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@11'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: npm run coverage
      - codecov/upload:
          file: coverage/*.json
          flags: frontend